BEGIN;

DROP TABLE IF EXISTS ActualLecturers;
DROP TABLE IF EXISTS Marks;
DROP TABLE IF EXISTS Lecturers;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Groups;

END;
